/**
 * Application constants
 * Configuration loaded from environment variables.
 *
 * Network-aware: the active network (testnet / local) is stored in
 * `networkStore`. Static exports below are the **testnet defaults** used
 * during module init.  For runtime-dynamic access (e.g. when the user
 * switches to a local quickstart node), use the `getActive*` helpers.
 */

import { getRuntimeConfig } from './runtimeConfig';
import {
  getActiveNetworkConfig,
  getActiveNetwork,
  getActiveContractId,
  isLocalNetwork,
  type StellarNetwork,
} from '@/store/networkStore';

export { getActiveNetwork, isLocalNetwork, type StellarNetwork };

const runtimeConfig = getRuntimeConfig();

export const SOROBAN_RPC_URL =
  runtimeConfig?.rpcUrl || import.meta.env.VITE_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org';
export const RPC_URL = SOROBAN_RPC_URL; // Alias for compatibility
export const NETWORK_PASSPHRASE =
  runtimeConfig?.networkPassphrase ||
  import.meta.env.VITE_NETWORK_PASSPHRASE ||
  'Test SDF Network ; September 2015';
export const NETWORK = SOROBAN_RPC_URL.includes('testnet') ? 'testnet' : 'mainnet';

function contractEnvKey(crateName: string): string {
  // Crate name -> env key matches scripts/utils/contracts.ts: hyphens become underscores.
  const envKey = crateName.replace(/-/g, '_').toUpperCase();
  return `VITE_${envKey}_CONTRACT_ID`;
}

export function getContractId(crateName: string): string {
  const runtimeId = runtimeConfig?.contractIds?.[crateName];
  if (runtimeId) return runtimeId;
  const env = import.meta.env as unknown as Record<string, string>;
  return env[contractEnvKey(crateName)] || '';
}

export function getAllContractIds(): Record<string, string> {
  const env = import.meta.env as unknown as Record<string, string>;
  const out: Record<string, string> = {};

  if (runtimeConfig?.contractIds) {
    for (const [key, value] of Object.entries(runtimeConfig.contractIds)) {
      if (!value) continue;
      out[key] = value;
    }
  }

  for (const [key, value] of Object.entries(env)) {
    if (!key.startsWith('VITE_') || !key.endsWith('_CONTRACT_ID')) continue;
    if (!value) continue;

    const envKey = key.slice('VITE_'.length, key.length - '_CONTRACT_ID'.length);
    const crateName = envKey.toLowerCase().replace(/_/g, '-');
    if (!out[crateName]) {
      out[crateName] = value;
    }
  }

  // Fall back to bindings-embedded contract ID when no .env / runtime config is set
  if (!out['cangkulan']) {
    // Lazy-import at module level (hoisted) — see `cangkulanNetworks` below
    out['cangkulan'] = _bindingsCangkulanId;
  }

  return out;
}

// Bindings-level fallback for cangkulan contract ID (generated by `bun run bindings`)
import { networks as cangkulanNetworks } from '@/games/cangkulan/bindings';
const _bindingsCangkulanId = cangkulanNetworks.testnet.contractId;

// Contract IDs
export const MOCK_GAME_HUB_CONTRACT = getContractId('mock-game-hub');
export const CANGKULAN_CONTRACT = getContractId('cangkulan') || _bindingsCangkulanId;
export const ZK_VERIFIER_CONTRACT = getContractId('zk-verifier') || 'CA7RTG6G2WRKNKMJ57CAYWWC7IH3ZVIOLWVIUOMDTI65GMKGVO5YGRBM';
export const GAME_HUB_CONTRACT = getContractId('mock-game-hub') || 'CB4VZAT2U3UC6XFK3N23SKRF2NDCMP3QHJYMCHHFMZO7MRQO6DQ2EMYG';
export const LEADERBOARD_CONTRACT = getContractId('leaderboard') || 'CDZNFIVDP5VJCD2YKPSY6ZHELGXJQVJK7NBI2S56PMK4QB4PIBMICVHB';
export const ULTRAHONK_VERIFIER_CONTRACT = getContractId('ultrahonk-verifier') || 'CD52VAWNT5LP5S7CLTCFWOQ3FTOSNJMAUAQBTWPI4ECCR55S6LX6IZ6A';
export const STELLAR_EXPERT_BASE = 'https://stellar.expert/explorer/testnet/contract';

// Dev wallet addresses
export const DEV_ADMIN_ADDRESS = import.meta.env.VITE_DEV_ADMIN_ADDRESS || '';
export const DEV_PLAYER1_ADDRESS = import.meta.env.VITE_DEV_PLAYER1_ADDRESS || '';
export const DEV_PLAYER2_ADDRESS = import.meta.env.VITE_DEV_PLAYER2_ADDRESS || '';

// Runtime-configurable simulation source (for standalone builds)
export const RUNTIME_SIMULATION_SOURCE =
  runtimeConfig?.simulationSourceAddress || import.meta.env.VITE_SIMULATION_SOURCE_ADDRESS || '';

// Transaction options
export const DEFAULT_METHOD_OPTIONS = {
  timeoutInSeconds: 30,
};

// Auth TTL constants (in minutes)
export const DEFAULT_AUTH_TTL_MINUTES = 5;
export const MULTI_SIG_AUTH_TTL_MINUTES = 12;

// ═══════════════════════════════════════════════════════════════════════════════
//  Network-aware dynamic getters
//  Use these when the code must respect the active network (local vs testnet).
// ═══════════════════════════════════════════════════════════════════════════════

/** Returns the RPC URL for the currently-active network. */
export function getActiveRpcUrl(): string {
  return getActiveNetworkConfig().rpcUrl;
}

/** Returns the network passphrase for the currently-active network. */
export function getActivePassphrase(): string {
  return getActiveNetworkConfig().networkPassphrase;
}

/** Returns the contract ID for `crateName` on the active network. */
export function getActiveCangkulanContract(): string {
  return getActiveContractId('cangkulan', CANGKULAN_CONTRACT);
}

export function getActiveZkVerifierContract(): string {
  return getActiveContractId('zk-verifier', ZK_VERIFIER_CONTRACT);
}

export function getActiveGameHubContract(): string {
  return getActiveContractId('mock-game-hub', GAME_HUB_CONTRACT);
}

export function getActiveLeaderboardContract(): string {
  return getActiveContractId('leaderboard', LEADERBOARD_CONTRACT);
}

export function getActiveUltrahonkVerifierContract(): string {
  return getActiveContractId('ultrahonk-verifier', ULTRAHONK_VERIFIER_CONTRACT);
}

/** True when the URL is plain HTTP (e.g. local quickstart node). */
export function needsAllowHttp(url?: string): boolean {
  return (url ?? getActiveRpcUrl()).startsWith('http://');
}

/** Returns the Horizon URL for the active network. */
export function getActiveHorizonUrl(): string {
  return getActiveNetworkConfig().horizonUrl;
}

/** Returns the Friendbot URL for the active network. */
export function getActiveFriendbotUrl(): string {
  return getActiveNetworkConfig().friendbotUrl;
}

/**
 * Returns a Stellar Expert explorer link if on testnet.
 * @param type - 'tx' or 'contract'
 * @param id - The hash or contract ID
 */
export function getStellarExpertLink(type: 'tx' | 'contract', id: string): string | null {
  const activeNetwork = getActiveNetwork();
  if (activeNetwork !== 'testnet') return null;
  return `https://stellar.expert/explorer/testnet/${type}/${id}`;
}
